#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim='nvim' vimdiff='nvim -d'

# Use $XINITRC variable if file exists.
[ -f "${XINITRC}" ] && alias startx='startx ${XINITRC}'

# Verbosity and settings that you pretty much just always are going to want.
alias \
	mkd='mkdir -pv' \
  els='eza --long --header --inode --git' \
	yt='youtube-dl --add-metadata -ic' \
	yta='yt -x -f bestaudio/best' \
	ffmpeg='ffmpeg -hide_banner'

# Colorize commands when possible.
alias \
	diff='diff --color=auto' \

# These common commands are just too long! Abbreviate them.
alias \
	ka='killall' \
    ag='sudo apt-get' \
	g='git' \
	grepcljs='grep -rnT --include=\"*.cljs\"' \
	greppy='grep -rnT --include=\"*.py\"' \
	sshp='ssh -i .ssh/pi_id_ed25519 pi@192.168.100.23' \
	trem='transmission-remote' \
	YT='youtube-viewer' \
	sdn='sudo shutdown -h now' \
	zat='zathura' \
	f='${FILE}' \
	v='${EDITOR}' \
    r='yazi' \
  gcl="gcloud auth login --update-adc"\

# Commands that need command line arguments
alias \
    c='calcurse -D .local/share/calcurse -C .config/calcurse'

alias \
	magit='vim -c MagitOnly' \
	ref='shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc' \
	weath='less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport' \
	tmux='tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf' \

alias zshconfig='${EDITOR} ${ZDOTDIR}/.zshrc'
alias ohmyzsh='r ${ZSH}'

# Dates
alias dt='date +%Y%m%d'    # frequent 8-digit stamp: 20160114
alias dt8=dt
alias day=dt
alias dts='date +%s'       # seconds since epoch: 1452795263
alias dte=dts
alias dt10=dts
alias dtep='print "use this to parse: date -d @123..."'  # parse the epoch
alias dtp='date -Id '       # parse
alias dttm='date --utc +%Y%m%d%H%M%S'  # datetime: 20160114192940
alias dt14=dttm
alias dt13=dtb
alias dto='date +%Y%j'     # ordinal date: 2016016 (16th day of year)
alias dt7=dto
# https://en.wikipedia.org/wiki/ISO_week_date
alias dtwk='date +W%V'     # week date: W02
alias dtyrwk='date +%GW%V' # year week date: 2016W02
# ISO 8601
alias dtw='date +%G-W%V-%' # year week: 2016-W02-4
alias dti='date -I'        # ISO-8601: 2016-01-14
alias dt-=dti
alias dti='date -u +%Y%m%dT%H%M%S'        # 20160111T173110Z
alias dti-='date -u +%Y-%m-%dT%H:%M:%SZ'  # 2016-01-11T17:31:10Z
alias dti0='date -u -Iseconds'            # 2016-01-11T17:31:10+0000
alias dto-='date +%Y-%j'                  # ordinal date: 2016-016

# Chezmoi dotfile management
alias cz='chezmoi'
alias cza='chezmoi apply'
alias czd='chezmoi diff'
alias cze='chezmoi edit'
alias czs='chezmoi status'
alias czcd='cd ~/.local/share/chezmoi'
