general.import = [
    "~/.config/alacritty/themes/themes/challenger_deep.toml"
]

general.live_config_reload = true
working_directory = "None"

[font]
size = 18.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.85
option_as_alt = "Both"
startup_mode = "SimpleFullscreen"
title = "Alacritty"
